/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyLithuaniaRouteImport } from './routes/why-lithuania'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as StudyAbroadRouteImport } from './routes/study-abroad'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LithuaniaRouteImport } from './routes/lithuania'
import { Route as FintechRouteImport } from './routes/fintech'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhyLithuaniaRoute = WhyLithuaniaRouteImport.update({
  id: '/why-lithuania',
  path: '/why-lithuania',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadRoute = StudyAbroadRouteImport.update({
  id: '/study-abroad',
  path: '/study-abroad',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LithuaniaRoute = LithuaniaRouteImport.update({
  id: '/lithuania',
  path: '/lithuania',
  getParentRoute: () => rootRouteImport,
} as any)
const FintechRoute = FintechRouteImport.update({
  id: '/fintech',
  path: '/fintech',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fintech': typeof FintechRoute
  '/lithuania': typeof LithuaniaRoute
  '/login': typeof LoginRoute
  '/recruitment': typeof RecruitmentRoute
  '/students': typeof StudentsRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/universities': typeof UniversitiesRoute
  '/why-lithuania': typeof WhyLithuaniaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fintech': typeof FintechRoute
  '/lithuania': typeof LithuaniaRoute
  '/login': typeof LoginRoute
  '/recruitment': typeof RecruitmentRoute
  '/students': typeof StudentsRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/universities': typeof UniversitiesRoute
  '/why-lithuania': typeof WhyLithuaniaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fintech': typeof FintechRoute
  '/lithuania': typeof LithuaniaRoute
  '/login': typeof LoginRoute
  '/recruitment': typeof RecruitmentRoute
  '/students': typeof StudentsRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/universities': typeof UniversitiesRoute
  '/why-lithuania': typeof WhyLithuaniaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/fintech'
    | '/lithuania'
    | '/login'
    | '/recruitment'
    | '/students'
    | '/study-abroad'
    | '/universities'
    | '/why-lithuania'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/fintech'
    | '/lithuania'
    | '/login'
    | '/recruitment'
    | '/students'
    | '/study-abroad'
    | '/universities'
    | '/why-lithuania'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/fintech'
    | '/lithuania'
    | '/login'
    | '/recruitment'
    | '/students'
    | '/study-abroad'
    | '/universities'
    | '/why-lithuania'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FintechRoute: typeof FintechRoute
  LithuaniaRoute: typeof LithuaniaRoute
  LoginRoute: typeof LoginRoute
  RecruitmentRoute: typeof RecruitmentRoute
  StudentsRoute: typeof StudentsRoute
  StudyAbroadRoute: typeof StudyAbroadRoute
  UniversitiesRoute: typeof UniversitiesRoute
  WhyLithuaniaRoute: typeof WhyLithuaniaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-lithuania': {
      id: '/why-lithuania'
      path: '/why-lithuania'
      fullPath: '/why-lithuania'
      preLoaderRoute: typeof WhyLithuaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad': {
      id: '/study-abroad'
      path: '/study-abroad'
      fullPath: '/study-abroad'
      preLoaderRoute: typeof StudyAbroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lithuania': {
      id: '/lithuania'
      path: '/lithuania'
      fullPath: '/lithuania'
      preLoaderRoute: typeof LithuaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fintech': {
      id: '/fintech'
      path: '/fintech'
      fullPath: '/fintech'
      preLoaderRoute: typeof FintechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FintechRoute: FintechRoute,
  LithuaniaRoute: LithuaniaRoute,
  LoginRoute: LoginRoute,
  RecruitmentRoute: RecruitmentRoute,
  StudentsRoute: StudentsRoute,
  StudyAbroadRoute: StudyAbroadRoute,
  UniversitiesRoute: UniversitiesRoute,
  WhyLithuaniaRoute: WhyLithuaniaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
